# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5fg7DS7HSahXirn6PQszh-5OxRn7cfc
"""

numbers = list(range(1, 11))
print("The created list:",numbers)
first_five = numbers[:5]
reversed_five = first_five[::-1]
print("First five elements:", first_five)
print("Reversed elements:", reversed_five)